---
title: "lecture12_growth"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Consider the following model of forest growth (where forest size in measured in units of carbon (C))



dC/dt  = r*C for forests where carbon is below a canopy closure threshold 



dC/dt = g  for forests where carbon is  at or above the threshold canopy closure



dC/dt = 0 once a carrying capacity (K) is reached.







The size of the forest (C), Canopy closure threshold and carrying capacity are all in units of carbon 



You could think of the canopy closure threshold as the size of the forest at which growth rates change from exponential to linear



You can think of r, as early exponential growth rate and g as the linear growth rate once canopy closure has been reached

Here's what you will do



1. Implement this model in R (as a differential equation)



2. Run the model for 300 years (using the ODE solver)  starting with an initial forest size of 10 kg/C, and using the following parameters



canopy closure threshold of 50 kgC 



 K = 250 kg C (carrying capacity) 



 r=  0.01 (exponential growth rate before before canopy closure)



 g = 2 kg/year (linear growth rate after canopy closure)



Graph the results



3. Run a sobol sensitivity analysis that explores how the estimated maximum and mean forest size (e.g maximum and mean values of C over the 300 years) varies with the pre canopy closure growth rate (r) and post-canopy closure growth rate (g) and canopy closure threshold and carrying capacity(K)

Assume that they are all normally distributed with means as given above and standard deviation of 10% of mean value

Graph the results of the sensitivity analysis as a box plot of maximum forest size and a plot of the two sobol indices (S and T)



Submit R markdown with model implementation, graphs and sensitivity analysis and R file with your model

