---
title: "Syllabus"
format: pdf
editor: visual
---

# Teaching Approach

Class will include a mix of lectures and in class hands-on examples, using students’ own computers. Discussion sections will elaborate on lecture topics and provide time for students to work on assignments with instructor and TA support.

# Teaching team

**Instructor:** Naomi Tague (https://tagueteamlab.org/)

-   **Office:** Bren Hall 4516
-   **Office hours:** email to set a time
-   **Email:** tague\@ucsb.edu

**Teaching assistant:** Ojas Sarup

-   **Office:** BH 4329 (Manzanita)
-   **Office hours:** Tuesday 2:00-4:00 PM
-   **Email:** ojassarup\@ucsb.edu

# Where we will be

-   **Lectures:** Tues, Thur 9:30-10:45 (**ES Seminar Room 4016**)\
-   **Discussion Section Friday** 9:00-10:20 (**BH 1424**)\

# Learning objectives

-   Gain familiarity with different types of models and the situations where you might use them

-   Understand how to choose the 'right model' for the job

-   Know how to build simple models including

    -   input-output models
    -   basic dynamic models

-   Gain some basic skills that are useful in applying models including

    -   parameter sensitivity analysis
    -   uncertainty analysis
    -   model calibration and evaluation

# Computing

-   I will assume that everyone has some basic R skills (from ESM 203, ESM 232, MEDS program courses or other courses), including how to use git, ggplot, and Quarto and build simple functions

-   Many classes will be working classes so bring laptop to class

-   All of the class material (example functions, data, and Quarto presentations from lectures) will be available on the course *github* site. I will update the repository before each class- so make sure you pull before class so you have access to all of the materials.

-   Here's the repo "<https://github.com/naomitague/EDS-230-ESM-232-W26.git>"

-   Remember that in *git* does not allow nested repositories - so *clone* the class site somewhere that it will not overlap with other repositories.

I recommend that you *fork* the repository so you can modify it and add to it; but keep an upstream remote so you can regularly sync with the class repository.

-   fork the course repo in your GitHub account

-   clone your fork to your computer

-   add upstream remote to original course repo

# ChatGPT and other AI-tools

There are pro's and con's to using AI-tools while you are learning environmental modeling (coding in general)

We will discuss and make use of these tools later in the course (mid-way)

Tools

-   Github Copilot (widely used by programmers)
-   ChatGPT

(both built from CODEX by OpenAI)

# Using AI-tools in this course

-   AI-tools great resources but effective use requires understanding how to ask good questions

-   Use this course to build that understanding, think about the meta concepts.

-   Ask yourself - What are situations you might apply a technique/idea/concept;

-   You gain skills by **Practicing**, so start without AI-tools

-   For assignments/practice

    -   **Always** write the code yourself -
    -   How we will use AI - tools later in the course
    -   Supportive ways to use AI-tools
        -   use AI-tools to help find syntax
        -   Use AI-tools to explain other peoples code (including class examples)
        -   Use AI-tools to help interpret error messages

# Attendance

-   You are expected to come to class - its part of the learning (pair-share)

-   We will regularly have in-class quizzes - These are not really "quizzes" where you answer is right or wrong. They are designed to help you think through the material and provide feedback to me as the instructor. For each quiz you will get full credit for attempting the question in class.

-   If you have to miss class, let Ojas and myself know by email

```{r, sch}
#| echo: false
#| message: false
#| warning: false

library(knitr)
library(kableExtra)

schedule <- data.frame(
`Week- Lecture#` = c("1-1","1-2","2-3","2-4","3-5","3-6","4-7","4-8","5-9","5-10","6-11","6-12","7-13","7-14","8-15","8-16","9-17","9-18","10-19","10-20"),
Date = c("Jan 6","Jan 8","Jan 13","Jan 15","Jan 20","Jan 22","Jan 27","Jan 29","Feb 3","Feb 5","Feb 10","Feb 12","Feb 17","Feb 19","Feb 24","Feb 26","March 3","March 5","March 10","March 12"),
`Lecture topics` = c(
"Intro: What is a model",
"Conceptual Models (no discussion)",
"Building Models",
"Informal Sensitivity Analysis",
"Multiple Parameter Variation",
"Multi-Component Models - Example RHESSys",
"Formal Sensitivity Analysis",
"Sensitivity Analysis Sobol (no discussion)",
"Guest Lecture",
"Dynamic Models - Analytical Solutions",
"Dynamic Models - ODE Solver",
"More on Dynamic Models",
"Sensitivity with Dynamic Models",
"Disturbance and Using Copilot tools ",
"2 Variable and Stability",
"Guest Lecture",
"What makes a good model",
"Calibration",
"Calibration2",
"Return to Big Picture"
),
Discussion = c("","Free","","Informal Sen","","Building Blocks","","Free","","Sobol Sen","","Output Summary","","Free","","Two-var Stability","","Calibration","",""),
check.names = FALSE
)

kable(
schedule,
format = "latex",
booktabs = FALSE,
align = c("l","l","l","l"),
caption = "\textbf{Tentative Course Schedule}"
) |>
row_spec(0, bold = TRUE) |>
kable_styling(latex_options = "hold_position")
```

# Assignments (Tentative Assign/Due Dates)

There are 9 assignment + weekly in class quizzes. Some assignments will be done in groups.

See Table Below

| Assign / Due     | Assignment                        | \% of Grade |
|------------------|-----------------------------------|-------------|
| Jan 6 / 8        | Getting to know you (Q/A)         | 5           |
| Jan 8 / 13       | Conceptual Model                  | 10          |
| Jan 15 / 22      | Almond Yield                      | 10          |
| Jan 22 / 27      | Almond Sensitivity                | 10          |
| Jan 29 / Feb 10  | Sobol and Sensitivity             | 10          |
| Feb 17 / 24      | Dynamic Model and Sensitivity     | 15          |
| Feb 17 / March 9 | Final Assignment: Model Plan      | 15          |
| Feb 24 / March 3 | Two-variable Dynamics             | 10          |
| March 5 / 10     | Model Calibration and Uncertainty | 5           |
| Throughout       | In-class Quizzes                  | 10          |
|                  | **Total**                         | **100**     |

Assignments will vary in length but most will be short coding assignments with a 1- paragraph write up.

Assignments will be submitted on [Canvas](https://www.canvas.ucsb.edu/) *Canvas* provides grading rubrics that you may find helpful.

[Here's the link to our courses Canvas site](https://ucsb.instructure.com/courses/30595) We will also use this for announcements

# Protocols and Guidance

-   Learning to program is hard and I may not always explain in a way that is accessible to you - So if you don't understand something *ASK*

-   Ideally ask in class - you will help me to learn how to explain (or find an answer if I don't know it) and you will help others

    -   if you don't feel comfortable asking , reach out to me or Ojas

-   Environmental modeling and the coding involved gets better with practice and play - Don't just read the Quatro - try the code, try variations on the ideas presented, make up stuff to try, get your feet wet

-   Programming means making mistakes, expect it, stay calm and try again - if you get frustrated step away and come back; be creative

-   **Respect and Support each other**

    -   when working in groups, pay attention to your partner, if they are not at your skill level, help them learn - recognize that we all have different backgrounds
    -   listen - different perspectives contribute to modeling - ask questions; figure out how different people *see* the world (what is there conceptual model)
    -   you learn by helping others - do that!

-   If you are really struggling, reach out to Ojas or myself, we can help (or if you just want to chat about something )

# Coding Best Practices

-   clear, readible (well-documented) code

-   informative variable and function names

-   graphs that are easy to understand (labels, legends, strategic use of color)

-   R code commenting

    -   see "papers/comments-guildelines-EDS220.pdf", for recommended practices
