---
title: "Syllabus "
output:
  slidy_presentation:
    highlight: pygments
  html_document: default
  beamer_presentation:
    highlight: pygments
  pdf_document: default
  ioslides_presentation:
    highlight: pygments
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Course description

<p style="color: #ba5e00"><b> Environmental Modelling: An overview.</p></b>

Models give us a way to look at the world through a mixture of data and theory. A good model can help us to understand how the world works and how decisions that we make might change the world in ways that are important to us. 


# Style

Class will include a mix of lectures and in class hands-on examples, using students’ own computers.

I will often provide an R-markdown document for you to go through prior to class so you can learn at your own pace and we will then use class time for the hands-on examples and assignments.


Class will include a mix of lectures and in class hands-on examples, using students’ own computers. I will often provide an R-markdown document for you to go through prior to class so you can learn at your own pace and we will then use class time for the hands-on examples and assignments.



# Teaching team

**Instructor:** Naomi Tague 
(https://tagueteamlab.org/)

-   **Office:** Bren Hall 4516
-   **Office hours:** email to set a time
-   **Email:** tague@ucsb.edu

**Teaching assistant:** Ojas Sarup

-   **Office:** Bren Hall 1005
-   **Office hours: ** TBA
-   **Email:** ojassarup@ucsb.edu 


# Where we will be

-   **Lectures:** Tues, Thur 8:00am - 9:15 am (**BH 1414**)  
-   **Discussion Section 1** Tues 1:00pm-2:00pm  (**BH 1510**)  
-   **Discussion Section 2** Tues 2:00pm-2:50pm  (**BH 1510**)  

please attend discussion section where. you signed up

      
# Learning objectives

 - Gain familiarity with different types of models and the situations where you might use them
 
 - Understand how to choose the 'right model' for the job
 - Know how to build simple models including
      - input-output models
      - basic dynamic models 
      - matrix models
      
  - Gain some basic skills that are useful in applying models including
      - parameter sensitivity analysis
      - uncertainty analysis
      - model calibration and evaluation
      


# Computing

-   I will assume that everyone has some basic R skills (from ESM 203, ESM 232, MEDS program courses or other courses), including how to use ggplot, and Rmarkdown and build simple functions

-   Many classes will be working classes so bring laptop to class

- Some of the material (example functions and Rmarkdown code) will also be available on *github*
I will also provide this material on *canvas* but if you are familiar with *git* then it may be faster to clone and then update the repository.  We will discuss this further when we get to this part of the course




# Tentative topics



| Week | Lecture topics | 
|------|----------------|
|April 2   | Into and Conceptual Models         | 
|April 9   | Constructing Simple Models in R         | 
|April 15    | Sensitivity Analysis      | 
| April 22   | Model Applications    | 
| Aprill 29. | Dynamic Models
| May 6  | Stability and Sensitivity with Dynamic Models        |
| May 13    |  Choosing and Evaluating Models |             
| May 20    |  Model Calibration |
| May 27    |   Optimization  | 
| June 3    |  Discrete Dynamic, Wrap Up    | 

# Assignments


There are 8 assignments. Some assignments will be done in groups. Assignments will vary in length but most will be short coding assignments with a 1- paragraph write up. 

Assignments will be submitted on 
[Canvas](https://www.canvas.ucsb.edu/)
*Canvas* provides grading rubrics that you may find helpful.

# Protocols and Guidance 

*  Learning to program is hard and I may not always explain in a way that is accessible to you - So if you don't understand something *ASK* 
    * ideally ask in class - you will help me to learn how to explain (or find an answer if I don't know it) and you will help others 
    * if you don't feel comfortable asking , reach out to me or Ojas

* Environmental modeling and the coding involved gets better with practice and play - Don't just read the Rmarkdown - try the code, try variations on the ideas presented, make up stuff to try, get your feet wet 

* Programming means making mistakes, expect it, stay calm and try again - if you get frustrated step away and come back; be creative


* **Respect and Support each other** 

  * when working in groups, pay attention to your partner, if they are not at your skill level, help them learn - recognize that we all have different backgrounds
  * listen - different perspectives contribute to modeling - ask questions; figure out how different people *see* the world (what is there conceptual model)
  * you learn by helping others - do that!
  
  

* If you are really struggling, reach out to Ojas or myself, we can help
(or if you just want to chat about something ) 


