---
title: "Assignment1"
output:
  pdf_document: default
  ioslides_presentation:
    highlight: pygments
  html_document: default
  slidy_presentation:
    highlight: pygments
  beamer_presentation:
    highlight: pygments
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---


# Intro 

1. Fill out *Help us get to know you* survey on
[Canvas](https://ucsb.instructure.com/courses/19594)

2. Listen to *only* timestap 26:27 to 31:22  (basically 5 minutes) of the following blog by Lisa Felman Barrett - a highly cited psychologist

    * [blog  26:27 to 31:22](https://youtu.be/NbdRIVCBqNI?t=1587)

    * if you are interested you can learn
[More about Lisa Felman Barrett](https://www.affective-science.org/lisa-feldman-barrett.shtml)

    * Think about what an inverse inference problem might be in the context of the environment



4. After listening to these podcast, do the following

Think of a conceptual model that you or someone else might use to understand some pattern that they observe in the environment (in other words a model that might help them to solve an inverse inference problem to understand the mechanisms that causes the observation)?

We will discuss in class


# This week's Discussion Section 

In this course, we will work a lot with writing and applying functions; You've all been exposed to writing functions in previous courses - but just to make sure that everyone remembers the basic syntax in R, complete the following:

    a. Write a function that computes energy produced from a photovoltaic system if you know the average annual solar radiation.  You can use the following formula: 

        $E = A * r * H * PR$
    
        * *E* is energy (kWh),
        * *A* is the solar panel area (m2)
        * *r* is panel yield (0-1) (manufacture efficiency - usually around 0.2),
        * *PR* is performance ratio (0-1) (accounting for site factors that impact efficiency usually around 0.75) 
        * *H* is annual average solar radiation (kWh)


    b. Write your function in R; make sure that you add documentation; include default values for *r* and *PR* in the function definition; save the function in a single file to upload to Canva.


### To summarize, submit the following by 8am April 4th:

1. Fill out 'get to know you' survey on Canvas  
2. A single R file that implements the solar energy yield function (on Canvas)


### *Grading Rubric*

* Completed Survey (10 pts total)
* Function implementation (20 pts total)
  * function written in R (5pts)
  * correct function syntax in R (5pts)
  * includes default values (5pts)
  * clear documentation (5pts)


