---
title: "Sobol Sensitivity Analysis Assignment"
output:
  pdf_document: default
  html_document: default
---


*Assignment Part I*

Choose one of the 3 papers below that provide an example of sensitivity analysis of model parameters.
*Or* find another paper that uses model sensitivity analysis as part of understanding an enviromental topic

After going through the paper, write a paragraph describing how results of the sensitivity analysis reported on in the paper might contribute to understanding (or prediction) within an environmental problem solving or management context.

Snow modeling

Building Cooling Energy Mdoel

Uranium in Groundwater Model

*Assignment Part 2*

Recall our model of atmospheric conductance $$
C_{at} = \frac{v_m}{6.25*{ln(\frac{z_m-z_d}{z_0})}^2}
$$ $$
z_d = k_d*h
$$ $$
z_0 = k_0*h
$$

$z_m$ is the height at which windspeed is measured - must be higher than the vegetation (cm), it is usually measured 200 cm above the vegetation

$h$ is vegetation height (cm)

$v$ is windspeed (cm/s)

Typical values if $k_d$ and $k_o$ are 0.7 and 0.1 respectively (so use those as defaults)

Your task

Repeat the sensitivity analysis that we have been working on in class BUT lets assume that we are in a different locations - where windpeeds are substantially higher and more variable AND vegetation is shorter - See details below

Consider the sensitivity of your estimate to uncertainty in the following parameters and inputs

$height$

$k_d$

$k_0$

$v$

Windspeeds $v$ are normally distributed with a mean of 300 cm/s with a standard deviation of 50 cm/s

For vegetation height assume that height is somewhere between 3.5 and 5.5 m (but any value in that range is equally likely)

For the $k_d$ and $k_0$ parameters you can assume that they are normally distributed with standard deviation of 1% of their default values

Use the Sobel approach to generate parameter values for the 4 parameters

Run the atmospheric conductance model for these parameters

Plot conductance estimates in a way that accounts for parameter uncertainty

Plot conductance estimates against windspeed use the parameter that is 2nd in terms of total effect on response

Estimate the Sobel Indices for your output

Comment on what this tells you about how atmospheric conductance and its sensitivity to variation in windspeed differs in this setting as compared to the setting that we examined in class where windspeed was lower and less variable and vegetation was taller.

Submit a pdf or html document with your code, graphs, and answers to the questions on Canvas
Due 

*Grading Rubric*. Total points 80. (normalized to 10 for Canvas)

**PART I (Paper Examples)**

* Discussion of the implication of parameter uncertainty from example paper 

  * explanation directly relates to a specific parameter (10pts)

  * explanation explores how parameter uncertainty might meaningfully impact results (10pts)

**PART II (Atmospheric Conductance and Sobol)**

* Generation of parameter values using Sobol (10pts)

* Running model for the parameters (10pts)

* Graph of uncertainty of the response variable

  * meaningful graph (5pts)

  * graphing style (axis labels, legibility) (5 pts)

* Graph of relationship between output and windspeed

  * choice of color (see instructions) (5pts)

  * graphing style (axis labels, legibility) (5 pts)

* Computing Sobol Indicators (10 pts)

* Discussion 

  * correctly identifying how sensitivity to windspeed changed with setting (10pts)

