---
title: "Almond Profit Model - Informal Sensitivity Analysis "
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment 4 - Almond Profit Model - Informal Sensitivity Analysis

In your same groups -

-   Develop a profit model for your almond yield (you can make this up - think about what the parameters would be)

    -   you might assume a baseline profit and then adjust according to the anomaly

    -   there are many ways to combine the almond yield and profit functions; you can have the profit function "call"/use the almond yield function; or create a wrapper function that calls them in sequence (first the almond yield and then the profit function)

-   Do a simple informal sensitivity analysis of almond yield profit using at least 2 parameters

-   Create a single graph of the results - you can decide what is the most meaningful graph

Submit as a group: pdf of rendered quarto including graph, your R files for almond yield and profit model,


# Grading Rubric

Profit model 

  * computes profit based on almond yield anomoly (1 pts)
  * implementation in R as a function with parameters (2 pts)
  * code runs without errors and is well documented (1 pt)
  

Workflow

  * models coupled - either a wrapper or workflow showing how yield/profit linked (1pt)
  * sensitivity analysis of at least 2 parameters 
      * sensitivity analysis includes sampling from distributions (or other source) for 2 parameters (2 pts)
      * clear well documented code (1 pt)
      
Graph

  * single graph showing sensitivity analysis results (1 pt)
  * graph is clearly labeled and easy to interpret (1 pt)
  
  Extra point for really interesting or novel graph
  
  
      
