---
title: 'Assignment: Using Sobol with an ODE'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Consider the following model of forest growth (where forest size in measured in units of carbon (C))

-   $dC/dt  = r*C$ for forests where C is below a threshold canopy closure

-   $dC/dt = g*(1- C/K)$ for forests where carbon is at or above the threshold canopy closure

-   and $K$ is a carrying capacity in units of carbon

The size of the forest ($C$), Canopy closure threshold and carrying capacity are all in units of carbon

You could think of the canopy closure threshold as the size of the forest at which growth rates change from exponential to linear You can think of $r$, as early exponential growth rate and $g$ as the linear growth rate once canopy closure has been reached

## [Your task]{style="color:orange"} {.scrollable}

1.  Implement this model in R (as a differential equation)

2.  Run the model for 300 years (using the ODE solver) starting with an initial forest size of 10 kg/C, and using the following parameters:

-   canopy closure threshold of 50 kgC
-   $K$ = 250 kg C (carrying capacity)
-   $r$= 0.01 (exponential growth rate before before canopy closure)
-   $g$ = 2 kg/year (linear growth rate after canopy closure)

3.  Graph the results. Here you are graphing the trajectory with the parameters as given (e.g no uncertainty)

4.  Run a sobol global (vary all parameters at the same time) sensitivity analysis that explores how the estimated **maximum forest size** (e.g maximum of $C$ 300 years, varies with these parameters

-   pre canopy closure growth rate ($r$)
-   post-canopy closure growth rate ($g$)
-   canopy closure threshold and carrying capacity($K$)

Assume that parameters are all normally distributed with means as given above and standard deviation of 10% of mean value

5.  Graph the results of the sensitivity analysis as a box plot of maximum forest size and record the two Sobol indices (**S** and **T**).

6.  In 2-3 sentences, discuss what the results of your simulation might mean. (For example think about how what parameters climate change might influence).

Submit rendered Quarto pdf with model implementation, graphs and sensitivity analysis and R file with your model

You can work in groups or individually

## Extra Credit

Compute Sobol indices for a second metric: forest size after a 100 years

## Grading Rubric


