---
title: 'Almond Yield as a Function '
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#  ASSIGNMENT 3 Almond Yields


Lobell et al., 2006 used data to build models of tree crop yield for California that captured how
climate variation (place and time) might influence yield


* Yield anomaly

* Climate variables

Assumptions...as you work think about what these are...


# Assignment


For this assignment you will work in *pairs*

Your goal is to implement a simple model of almond yield anomaly response to climate

* Inputs: daily times series of minimum, maximum daily temperatures and precipitation

* Outputs: maximum, minimum and mean yield anomoly for a input time series


The Lobell et al. 2006 paper will be the source for the transfer function that you will use in your model; specifically look at the equations in table 2.

# What you will do - Model Set Up

1. Draw diagram to represent your model - how it will translate inputs to outputs, with parameters that shape the relationship between inputs an outputs - on your diagram list what your inputs, parameters and outputs are with units

2.  Implement your diagram as an R function

Here are some ideas to think though. The climate data is going to need to be processed (e.g note that the model uses climate data from a particular month - you have ALL of the climate as daily data).  Here are two possible model outlines to follow

●      Almond_model <- function(clim_var1, clim_var2, parameters){……}

●      Almond_model <- function(clim, parameters){……}


The first example is where the climate variables are separately input into the function - climate data is processed beforehand as part of model set up

The second is where a climate data frame is the input to the function and you extract the useful data from it as part of the model. 


You can pick which option you prefer (or try both)
If you want a coding challenge, you could  create a model that works for any crop



# Run the model

3.  Run your model for the **clim.txt** data that is posted on Canvas, 

**clim.txt** has the following columns 

these 4 columns tell you when climate observations were made 

* *day*
* *month*
* *year* 
* *wy* (water year) 


the next 3 columns are the climate observations

* maximum (*tmax_c*) daily temperature 
* minimum (*tmin_c*) daily temperature 
* precipitation (*precip*) on that day in mm

# check your work 

I will tell you that

* the maximum almond yield anomaly should be approximately 1920 ton/acre
* the lowest almond yield anomaly should be approximately -0.027 ton/acre
* the mean almond yield anomaly should be approximately 182 ton/acre


#  Notes



* There are always multiple ways to code something in R;

* Remember that we want to strive for our code being as simple and streamline as possible. 

* Style counts. 
  * Make sure you choose meaningful variable names and add comments. 
  * Include comments at the top of the function to tell the user what the inputs/outputs are and their units and format.

# What to hand in on Canvas 

Two separate files (or a link to a repository with these files)

1. a R file that has your function definition
2. a pdf that includes your conceptual model (embed as picture), your workflow for running the model and
shows how you applied the function to the test climate data (*clim.txt*)

Due January 22 8am50
# Grading Rubric

Conceptual model (20 pts)

  * a clear diagram that corresponds with your R function (10 pts)
  * inputs and output and parameters shown on the diagram (10 pts)
  
R Implementation (30 pts)

  * correct function implementation (*.R file)  (10 pts)
  * application of the function to **clim.txt** (in Rmarkdown file) (10 pts)
  * coding practices (clear documentation, informative variables names)  (10 pts)
  

