---
title: "Assignment1-Preclass"
output:
  html_document: default
  ioslides_presentation:
    highlight: pygments
  pdf_document: default
  slidy_presentation:
    highlight: pygments
  beamer_presentation:
    highlight: pygments
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---


# Pre-Class Assignment

* Fill out *Help us get to know you* survey on *Canva*

* Listen to *only* timestap 26:27 to 31:22  (basically 5 minutes) of the following 
blog by Lisa Felman Barrett - a highly cited psychologist

* [blog  26:27 to 31:22](https://www.youtube.com/watch?v=NbdRIVCBqNI)

if you are interested you can learn
[More about Lisa Felman Barrett](https://www.affective-science.org/lisa-feldman-barrett.shtml)

Think about what an inverse inference problem might be in the context of the environment

* Listen to this podcast on climate models - Pay particular to how Gavin Schmidt talks about the design, goal and **skill** of models

[The emergent pattersn of climate change](https://www.ted.com/talks/gavin_schmidt_the_emergent_patterns_of_climate_change?language=en)


If you are interested you can learn
[More about Gavid Schmidt](https://www.giss.nasa.gov/staff/gschmidt/)



After listening to these podcast, do the following

1. Think of a conceptual model that you or someone else might use to understand some pattern that they observe in the environment (in other words a model that might help them to solve an inverse inference problem to understand the mechanisms that causes the observation)?

2. Draw a figure that represents the model - add as much detail as you can about what  inputs, mechanisms and outputs of the model (outputs would likely be the observation, inputs would be something about the environment and mechanisms could be the "how" that changes the inputs (causes) into output (observations))

3. Submit you figure on Canva (Assignment 1) along with 2-3 sentences that describe how this model might be used to understand some observation (or pattern of observations) in the environment 

A few notes:

You can make this as simple or challenging as you like. 

If you don't quite 'get it', don't worry - there isn't a 'right' answer here. Be creative and come up with your best interpretation

4. In this course, we will work a lot with writing and applying functions; You've all been exposed to writing functions in previous courses - but just to make sure that everyone remembers the basic syntax in R, complete the following:

Write a function that computes energy produced from a photovoltaic system if you know the average annual solar radiation.  You can use the following formula

E = A * r * H * PR

* *E* is energy (kWh),
* *A* is the solar panel area (m2)
* *r* is panel yield (0-1) (manufacture efficiency - usually around 0.2),
* *PR* is performance ratio (0-1) (accounting for site factors that impact efficiency usually around 0.75) 
* *H* is annual average solar radiation (kWh)

Write your function in R; make sure that you add documentation; include default values for *r* and *PR* in the function definition; save the function in a single file to upload to Canva.

**Important** If you need help with this Rachel will be holding office hours

To summarize, submit the following by April 14th

* your conceptual model figure 
* 2-3 sentences describing how it might be used
* a single R file that implements the solar energy yield function


*Grading Rubric*

* Conceptual model (30 pts total)
  * model diagram submitted (10 pts)
  * diagram aesthetics (easy to see, clear labels) (10 pts)
  * diagram shows model inputs and output (10 pts)
* Explanation of conceptual model (10 pts total)
  * explanation for the conceptual model provided (5pts)
  * explanation mentions observations and causes (5pts)
* Function implementation (20 pts total)
  * function written in R (5pts)
  * correct function syntax in R (5pts)
  * includes default values (5pts)
  * clear documentation (5pts)
