---
title: "Assignment 7 - Two Variables ODE"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

## Assignment {.scrollable}

Consider how you might add hunting of prey to the predator prey model that we've been using in class

**Part 1**:

Build this model (e.g add hunting to the lotvmodK.R),

Some requirements/hints for your model

You should make sure that you don't hunt more prey than exist.

To ensure that you might also add a minimum prey population input that must be met before hunting is allowed.

Note you can make this as simple or as complex as you would like. You could represent hunting in a way that is similar to "harvesting" in the last assignment - or you could make hunting an exogenous process - so a time based input to your model

**Part 2**

Explore how different hunting levels and uncertainty/variation in parameters in your model are likely to effect the stability of the populations of both predator and prey. A key challenge is how you might want to define stability? It is up to you but you will need to write a sentence to explain why you chose the measure that you did. It could be something as simple as maintaining a population above some value 50 years into the future. 

Use this exploration to recommend a hunting target that will be sustainable (e.g leave you with a stable prey and predator population).

It is up to you how you "explore" hunting - you can simply try different values of the parameters in your hunting model or do it more formally by running your model across a range of values. You could think about parameter interactions

You can assume the following are best guesses of key parameters

rprey=0.95, alpha=0.01, eff=0.6,pmort=0.4, K=2000,

Submit - the Quato document with your analysis AND a pdf/html version, any R files This should include

a)  your hunting model

b)  your exploration (e.g how you tested different hunting levels and how you defined a stability metric

c)  provides you estimated sustainable hunting level and brief explanation of why you chose the metric you did

# Alternative Assignment

Develop your own 2-vary dynanmic model of an enviromental process you are interested in

Explore how parameters in your model impact the outcomes of your model. Include a measure of "stability" as one of the outcomes - you can define stability however you like

Write a brief summary about what your model and sensitivity analysis tell you

# Grading

Your grade will be based on the following criteria (note for alternative assignment breakdown will be adapted to fit model)

| Criteria | Full Marks | No Marks | Points |
|----|----|----|----|
| **Adding hunting to pred-prey differential equation** <br> - Correct implementation (including adding parameters and modifying the equation) <br> - Includes a parameter to restrict hunting if prey falls below some value | 3 pts | 0 pts | 3 pts |
| **Developed a metric to quantify stability** <br> - The metric captures some aspect of stability <br> - The metric is implemented as a function that can be applied to a time series (or multiple time series) | 3 pts | 0 pts | 3 pts |
| **Exploration of stability** <br> - Compared the stability metric across different values of parameters used to define hunting <br> - Comparison is explicit in the Rmarkdown (graph or table) showing how hunting levels influence stability | 4 pts | 0 pts | 4 pts |
| **Using results to make conclusions** <br> - 1–2 sentences that justify a decision or policy about the level of hunting that clearly arise from the exploration of stability | 3 pts | 0 pts | 3 pts |
| **Style** <br> - Graphs have clear labels and legends (if needed) and clearly communicate the intended message <br> - Rmarkdown includes text explaining each step leading to the final conclusion about hunting levels | 2 pts | 0 pts | 2 pts |
|  |  | **Total Points** | **15 pts** |
