---
title: "Discussion_Section_Conceptual_Models"
format: revealjs
editor: visual
---

# Conceptual Models

* What is the goal of your model? Understanding, prediction, communication) of what?

Conceptual models guides

* What variables, interactions between variables or processes in complex reality are your going to consider? why?




# Conceptual Models: Things to think about

-   What inputs/parameters will influence how a process/mechanism leads to the outputs you are interested in

-   Can you measure those inputs/parameters? If not is there a proxy? Or another model?

-   Are there features of the environment that influence the relationship between input/parameter and output?

-   Are there inputs/parameters that you want to include to develop scenarios (things you'd want to 'change')

-   Time and Space (are you looking at a short or long terms behavior? do you care about spatial patterns? at what scale?)

-   What are some key assumptions?

# Conceptual model as a figure
 
Pictorial representation your conceptual model 
  * what are inputs
  * what are outputs
  * how do you get from inputs to outputs
  * are there internal variables/processes
  * are there interactions / relationships between variables 
  
Picture that shows what needs to be included in the model to answer your questions (or achieve your modelling goal)

# Task 1
-   Form groups of 3
-   With your group, come up with a modeling goal
-   Decide if the goal is understanding,prediction or communication
-   Brainstorm on important
    -   inputs, parameters and outputs
    -   relationships/processes
    -   assumptions
- Write it down and sketch (either on computer or on a piece of papers) 

# Task 2

Share your modeling goal and conceptual model with another group

Provide feedback - did they miss anything? Does it make sense? 


# More formal diagrams


\[Diagrams.net\]{[https://www.diagrams.net/}](https://www.diagrams.net/})

# Task 3 Complete and Submit as Group Assignment 2 - Conceptual Model


-   Write down the question that your model will answer
-   List the key inputs, parameters and outputs (as precisely as possible, think about space and time)
-   Sketch the underlying conceptual model that would relate inputs/parameters to the outputs
-   Decide what "type" of model it is based on classification discussed in class

Please submit as a pdf
**Important** - have the diagram on its own page!

- its up to you how you create the pdf
  * note you can create this by rendering a quarto document - good practice - as we will do this for other assignments in the course
  
Submit as a Group Assignment on Canvas by Monday April 7th 5pm
