
library(tm)
library(SnowballC)
library(RColorBrewer)
library(wordcloud)
docs = Corpus(VectorSource(pt$goal))
docclean = tm_map(docs, PlainTextDocument)
docclean = tm_map(docclean, tolower)
docclean = tm_map(docclean, removeNumbers)
docclean = tm_map(docclean, removeWords, stopwords("english"))
docclean = tm_map(docclean,  removePunctuation)
docclean = tm_map(docclean, removeWords, "models")
docclean = tm_map(docclean, removeWords, c("models","environmental","bren"))
docclean = tm_map(docclean, removeWords, c("model","and","have","for","more","the","are","environment","model"))
docclean = tm_map(docclean, removeWords, c("feel","i\'m","course","will","start","come","helpful"))
docclean = tm_map(docclean, removeWords, c("hope","need","i'm","the","modelling","course"))
docclean = tm_map(docclean, removeWords, c("environment","model","also","i'm","get","models","can","also","like"))
docclean = tm_map(docclean, removeWords, c("hope","need","i'm","the","modelling","course", "modeling","able", "excited","gain"))
docclean = tm_map(docclean, removeWords, c("especially","hoping","learning","interested","want"))
wordcloud(docclean, max.words=200, random.color=FALSE, random.order = FALSE, colors=brewer.pal(8,"Dark2"))


