---
title: "Sobol_literature_assigment"
output: html_document
date: "2023-05-03"
---

# Assignment

There are 3 peer reviewed articles (see attached files) that provide examples of using  Sobol Sensitivity analysis in the context of environmental modeling

 Choose 1 of these 3 articles - read with the goal of understanding how the paper used sensitivity analysis as part of their overall modeling objective.  (For the assignment just pick one article but I encourage you to at least skim all 3 to become more familiar with the use of sobol in environmental modeling)

In places the articles are technical and may discuss processes that you may not be familiar with (note that the snow article also discusses calibration and the energy  article also presents an another sensitivity method) -  you can skim as needed - your goal is  see how sobol sensitivity analysis is used 

In a paragraph

  * cite the paper

  * 1-2 sentences - describe the goal of the model application (20 pts)

  * 2-3 sentences - summarize what the sobol indices tell you about the influence of parameters on process/mechanisms/response being modeled (40pts)

* 1-2 sentences - suggest one reason why we might care about parameter importance in this context (e.g  what might be the implications of high sensitivity of a particular parameter) (40 pts)

Submit on Canvas

Review the *simpledynamic.Rmd* on ESM232_examples
