---
title: "assign_LHS_answer"
output: html_document
date: "2023-05-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sensitivity)
library(tidyverse)
library(gridExtra)
library(purrr)
library(lhs)
library(ggpubr)
```

# Example (Using Function from Last Assignment)

Atmospheric Conductance as a function of windspeed, vegetation height and parameters


```{r setsen, echo=TRUE, eval=TRUE}
source("../R/Catm.R")


# set a random seed to make things 'random'
set.seed(1)

# which parameters
pnames <- c("k_o", "k_d", "v", "height")

# how many parameters
npar <- length(pnames)
# how many samples
nsample <- 100

parm_quant <- randomLHS(nsample, npar)
colnames(parm_quant) <- pnames
# choose distributions for parameters - this would come from
# what you know about the likely range of variation
# then use our random samples to pick the quantiles

parm <- as.data.frame(matrix(nrow = nrow(parm_quant), ncol = ncol(parm_quant)))
colnames(parm) <- pnames
# for each parameter pick samples
# I'm using several examples normal distribution (with 10% standard deviation) and uniform with +- 10%
# in reality I should pick distribution from knowledge about uncertainty in parameters

# to make it easy to change i'm setting standard deviation / range variation to a variable
pvar <- 10

parm[, "k_o"] <- qnorm(parm_quant[, "k_o"], mean = 0.1, sd = 0.1 * 0.1)
parm[, "k_d"] <- qnorm(parm_quant[, "k_d"], mean = -0.7, sd = 0.7 * 0.1)
parm[, "v"] <- qnorm(parm_quant[, "v"], mean = 200, sd = 10)
parm[, "height"] <- qunif(parm_quant[, "height"], min = 5, max = 15)


head(parm)

# run for all parameters
conductance <- parm %>% pmap(Catm)
# because its just a list of single numbers
conductance <- unlist(conductance)

conductance <- cbind.data.frame(parm, conductance = conductance)
```

Sensitivity Quantification and Plotting

```{r sens}
# boxplot
ggplot(conductance, aes(conductance)) +
  geom_boxplot()

# cumulative distribution
ggplot(conductance, aes(conductance)) +
  stat_ecdf()

# scatter plots
tmp <- conductance %>% gather(-conductance, key = "parm", value = "parmvalue")
ggplot(tmp, aes(parmvalue, conductance, col = parm)) +
  geom_point() +
  facet_wrap(~parm, scale = "free")

# quantify
sens <- pcc(parm, conductance$conductance, rank = TRUE)

# nice to add to plot
ggplot(tmp, aes(parmvalue, conductance, col = parm)) +
  geom_point() +
  facet_wrap(~parm, scale = "free")

stext <- data.frame(parm = pnames, round(sens$PRCC, digits = 2))
ggplot(tmp, aes(parmvalue, conductance, col = parm)) +
  geom_point() +
  facet_wrap(~parm, scale = "free") +
  geom_text(data = stext, mapping = aes(x = -Inf, y = -Inf, label = original, hjust = -0.2, vjust = -12))
```

